// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkstAUXpViP6fCJFNglbQKHzKSEwVw4VI',
    appId: '1:495770030559:web:b7ddc7edaf7db4877e746a',
    messagingSenderId: '495770030559',
    projectId: 'zam-learn-it',
    authDomain: 'zam-learn-it.firebaseapp.com',
    storageBucket: 'zam-learn-it.firebasestorage.app',
    measurementId: 'G-THLNN0TY37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrMdoCi54ZAcJpMoHbsbNogrRzP9l2_g',
    appId: '1:495770030559:android:31cb9364e22cf58b7e746a',
    messagingSenderId: '495770030559',
    projectId: 'zam-learn-it',
    storageBucket: 'zam-learn-it.firebasestorage.app',
  );
}
